#runtime: python39 # or another supported version for standard environment
runtime: python
runtime_config:
    python_version: 3
env: flex
entrypoint: gunicorn -b :$PORT main:app

#instance_class: F4_1G
resources:
  memory_gb: 2

env_variables:
  BUCKET_NAME: "word2vec_id"
  DICT_ALL_COUNT: "all_1-200-000_word_count_sudachi.pickle"
  WORD2VEC: "mecab_word2vec_dict_100d.pickle"

readiness_check:
  app_start_timeout_sec: 1200

# Lock instances to 1
manual_scaling:
    instances: 1